Handle UnicodeDecodeError: replace comment text with a link to the original comment
Was needed to handle http://code.google.com/p/kryo/issues/detail?id=79#c2
which contains an invalid unicode char, processing this comment failed with

    File "./migrateissues.py", line 210, in pre_innerhtml
        return elem.html().strip().replace('<pre>', '').replace('</pre>', '')
    File "/usr/lib/python2.7/site-packages/pyquery/pyquery.py", line 933, in html
        for e in children])
    File "lxml.etree.pyx", line 3115, in lxml.etree.tostring (src/lxml/lxml.etree.c:63712)
    File "serializer.pxi", line 137, in lxml.etree._tostring (src/lxml/lxml.etree.c:100431)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 99: invalid continuation byte